language: generic

sudo: false

git:
    quiet: true

branches:
  except:
    - gh-pages

services:
  - docker

script:
  - docker build -t android-ndk:latest .
  - docker run -d --name android-ndk-container android-ndk
  - docker cp -a android-ndk-container:/tmp/libs HOME
  - ls -las /tmp/libs
